const data = {
    products:[
        {
            _id: '1',
            name: 'T-shirt',
            category: 'T-shirts',
            images: '/images/jacket.png',
            price: 120,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '2',
            name: 'Shirt',
            category: 'T-shirts',
            images: '/images/jacket.png',
            price: 120,
            countInStock: 0,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '3',
            name: 'T-shirt',
            category: 'T-shirts',
            images: '/images/jacket.png',
            price: 120,
            countInStock: 20,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '4',
            name: 'Polo T-shirt',
            category: 'T-shirts',
            images: '/images/jacket.png',
            price: 120,
            countInStock: 120,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '5',
            name: 'T-shirt',
            category: 'T-shirts',
            images: '/images/jacket.png',
            price: 120,
            countInStock: 120,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Nike T-shirt',
            category: 'T-shirts',
            images: '/images/jacket.png',
            price: 120,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        }
    ],
};
export default data;